apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pingspace-horizon
  namespace: pingspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingspace-horizon

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: pingspace-horizon
    spec:
      containers:
      - name: horizon
        image: your-docker-image
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: laravel-config
        env:
        - name: START_HORIZON
          value: "true"
        - name: RUN_LARAVEL_CRON
          value: "false"
        - name: START_NGINX
          value: "false"

      imagePullSecrets:
      - name: docker-auth
